### ISSUE TITLE
Thanks! but your usage instruction is not clear

### ISSUE THREAD

**Issue by thiyagaraaj** [TensorTom/colabctl#4]
Hello,

I could not understand your usage instruction.

**First, add your Colaboratory URLs to notebooks.csv.**

-> I created notebooks.csv through google spreadsheet, and put my notebook's url which i need to schedule.

**In colab, go to tools -> keyboard shortcuts and set "Clear all outputs" to CTRL + SHIFT + Q**

Done

**In colab, go to tools -> keyboard shortcuts and set "Reset all runtimes" to CTRL + SHIFT + k**

There is nothing like reset all runtimes. But there is restrart runtime and run all cells.  I have added this shortcut there. Dont know if i am right.

**At the end of your notebook, add: print("forkin"+"me")**

you mean in the notebook which i need schedule running?

**Now you're ready:

python colabctl.py <end-string> <sleep-seconds>

Example:

python colabctl.py forkinme 1800**

- Completely not understood the above... Kindly be clear so that your work will be useful to everyone. 

Waiting for your response. 

Thank you for your support

**Comment by aaron-makowski** [comment]
[Explanation of `print("forkin"+"me")`](https://media.tenor.com/images/5e2ec4cc934d4749ee3b65d91743c33c/tenor.gif)
